name: order_client_app
description: order Client App by Hesham Elnemr

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0

environment:
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_swiper: ^1.1.6
  google_maps_flutter: ^0.5.26+2
  mvc_pattern: ^5.0.0
  global_configuration: ^1.5.0
  http: ^0.12.0+4
  intl: '>=0.15.8 <=0.16.1'
  html: ^0.14.0+3
  shared_preferences: ^0.5.7
  flutter_html: ^0.11.1
  flutter_svg: ^0.17.4
  location: ^3.0.2
  dynamic_theme: ^1.0.1
  flutter_inappbrowser: ^2.0.2
  url_launcher: ^5.4.5
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.11
  cached_network_image: ^2.0.0+1
  flushbar: ^1.10.0
  liquid_pull_to_refresh: ^1.1.2
  rounded_loading_button: ^1.0.4
  flutter_local_notifications: ^1.4.1
  flare_splash_screen: ^3.0.1
  firebase_dynamic_links: ^0.5.0+11
  overlay_support: ^1.0.3
  flare_flutter: ^2.0.3
  flutter_staggered_grid_view: ^0.3.0
  my_fatoorah: ^2.1.0
  device_info: ^0.4.2+2
  flutter_rating_bar: ^3.0.1+1
  image_picker: ^0.6.5
  font_awesome_flutter: ^8.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/visa.png
    - assets/img/paypal.png
    - assets/img/paypal2.png
    - assets/img/apple_pay.png
    - assets/img/brazil.png
    - assets/img/canada.png
    - assets/img/china.png
    - assets/img/france.png
    - assets/img/germany.png
    - assets/img/italy.png
    - assets/img/netherlands.png
    - assets/img/spain.png
    - assets/img/united-arab-emirates.png
    - assets/img/united-states-of-america.png
    - assets/img/marker.png
    - assets/img/my_marker.png
    - assets/img/mastercard.png
    - assets/img/visacard.png
    - assets/img/wallet.png
    - assets/img/cash.png
    - assets/img/pay_pickup.png
    - assets/img/default.png
    - assets/img/default_food.png
    - assets/img/rate.png
    - assets/img/load.gif
    - assets/flare/
    - assets/graphics/strikethrough.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Tajawal
    fonts:
      - asset: assets/fonts/Tajawal-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/Tajawal-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Tajawal-Light.ttf
        weight: 300
      - asset: assets/fonts/Tajawal-Regular.ttf
        weight: 400
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 500
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 600
      - asset: assets/fonts/Tajawal-Bold.ttf
        weight: 700
      - asset: assets/fonts/Tajawal-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Tajawal-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
